name: update-readme

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dateutils
      run: sudo apt-get install dateutils

    - name: Log current README.md before update
      run: |
        echo "Logging the current README.md before update:"
        cat README.md

    - name: Calculate and update uptime
      run: |
        BIRTHDATE="2003-11-08"
        TODAY=$(date +%Y-%m-%d)
        UPTIME=$(dateutils.ddiff "$BIRTHDATE" "$TODAY" -f '%yy %mm %dd')
        echo "Calculated Uptime: $UPTIME"
        sed -i "s/{{ uptime }}/$UPTIME/g" README.md
        echo "Updated uptime in README.md"

    - name: Log current README.md after update
      run: |
        echo "Logging the updated README.md after update:"
        cat README.md

    - name: Commit and push changes
      run: |
        git config --global user.name 'paullyy8'
        git config --global user.email 'ap2952702@gmail.com'
        git add README.md
        git commit -m "Updated uptime and GitHub stats"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
